version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:7331/api
    ports:
      - "9745:9745"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=9745
      - REACT_APP_API_URL=http://localhost:7331/api
    depends_on:
      - backend
    networks:
      - portfolio-network

  backend:
    build:
      context: ./backend
    ports:
      - "7331:7331"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=7331
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - db
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    networks:
      - portfolio-network

  db:
    image: mysql:8.0
    ports:
      - "3370:3370"
    command: --port=3370
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=portfolio
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql-data: 